# Generated by Django 6.0.2 on 2026-03-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainTrust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('trust_score', models.CharField(max_length=20)),
                ('reason', models.TextField()),
                ('Checked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
